### ISSUE TITLE
Return to WelcomeView from CreateAccountView

### ISSUE THREAD

**Issue by DOOMNOTRON** [hunterthis/IslandStranded#13] opened 2022-08-15 19:18 UTC
Return back to welcome screen if you accidently select create account view.

**Comment by hunterthis** [comment] 2022-08-25 23:02
No longer returns to welcome screen, but instead just closes program. Couldn't figure out how to get the console app to shut down, unless installing further packages which I didn't want to add for one function. I'll leave the issue open in case it can get fixed later with a simpler soluation

**Comment by hunterthis** [comment] 2022-08-25 23:04
actually it functions as intended somewhat so ill close it for now

**Closed as completed by hunterthis** 2022-08-25 23:04 UTC
